# Generated by Django 4.2.4 on 2023-08-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_alter_conta_data_abertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=48, unique=True)),
                ('data_e_hora_processamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('vencimento', models.DateField()),
                ('situacao', models.CharField(max_length=12)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiario', to=settings.AUTH_USER_MODEL)),
                ('conta_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_beneficiario', to='cliente.conta')),
                ('conta_pagador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_pagador', to='cliente.conta')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pagador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
