# Generated by Django 4.2 on 2023-07-13 01:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_beneficiario', models.CharField(max_length=50)),
                ('conta_beneficiario', models.CharField(max_length=10)),
                ('banco', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_transacao', models.DateField(default=datetime.datetime(2023, 7, 12, 22, 46, 55, 59548))),
                ('tipo', models.CharField(max_length=15)),
                ('valor_transacao', models.FloatField()),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transacoes.beneficiario')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.conta')),
            ],
        ),
    ]
