# Generated by Django 4.2.4 on 2023-08-21 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_alter_conta_data_abertura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_transacao', models.DateField(default=datetime.datetime(2023, 8, 21, 12, 36, 31, 684875, tzinfo=datetime.timezone.utc))),
                ('tipo', models.CharField(max_length=15)),
                ('valor_transacao', models.FloatField()),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.conta')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
