# Generated by Django 4.2.4 on 2023-08-21 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_conta_data_abertura'),
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destino', to='cliente.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='origem', to='cliente.conta'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 13, 28, 55, 107055, tzinfo=datetime.timezone.utc)),
        ),
    ]
