# Generated by Django 4.2.3 on 2023-08-03 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2023, 8, 3, 11, 43, 51, 8089, tzinfo=datetime.timezone.utc)),
        ),
    ]
