# Generated by Django 4.2.4 on 2023-08-23 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0005_alter_transacao_data_hora_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 14, 31, 15, 68590, tzinfo=datetime.timezone.utc)),
        ),
    ]
