# Generated by Django 4.2.4 on 2023-08-24 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0006_alter_transacao_data_hora_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2023, 8, 24, 12, 1, 57, 498650, tzinfo=datetime.timezone.utc)),
        ),
    ]
