# Generated by Django 5.0.3 on 2024-03-08 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0009_alter_transacao_data_hora_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 14, 25, 3, 584983, tzinfo=datetime.timezone.utc)),
        ),
    ]
