# Generated by Django 5.0.4 on 2024-08-02 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0011_alter_transacao_data_hora_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2024, 8, 2, 22, 36, 38, 936002, tzinfo=datetime.timezone.utc)),
        ),
    ]
