# Generated by Django 5.0.4 on 2024-08-05 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacoes', '0012_alter_transacao_data_hora_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_hora_transacao',
            field=models.DateField(default=datetime.datetime(2024, 8, 5, 19, 29, 41, 634899, tzinfo=datetime.timezone.utc)),
        ),
    ]
