# Generated by Django 5.0.3 on 2024-03-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0012_endereco_tipo_alter_conta_data_abertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16, unique=True)),
                ('validade', models.DateField()),
                ('codigo_seguranca', models.CharField(max_length=3)),
                ('bandeira', models.CharField(default='MC', max_length=4)),
                ('limite', models.FloatField(default=0)),
                ('limite_usado', models.FloatField(default=0)),
                ('emissao', models.DateField()),
                ('endereco_cobranca', models.CharField(max_length=12)),
                ('status', models.CharField(default='BLOQUEADO', max_length=12)),
                ('tipo', models.CharField(max_length=15)),
                ('data_vencimento_fatura', models.DateField()),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.conta')),
            ],
        ),
    ]
