# Generated by Django 4.2.4 on 2023-08-15 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='banco',
            field=models.CharField(default='0934', max_length=4),
        ),
        migrations.AlterField(
            model_name='conta',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 9, 12, 49, 616359)),
        ),
    ]
