# Generated by Django 4.2 on 2023-07-13 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(max_length=12)),
                ('agencia', models.CharField(max_length=6)),
                ('saldo', models.FloatField()),
                ('data_abertura', models.DateField(default=datetime.datetime(2023, 7, 12, 22, 46, 55, 58803))),
                ('status_conta', models.CharField(max_length=12)),
            ],
        ),
    ]
