# Generated by Django 4.2.4 on 2023-08-15 12:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_conta_banco_alter_conta_chave_pix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 9, 35, 50, 66281)),
        ),
    ]
