# Generated by Django 4.2.4 on 2023-08-21 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16, unique=True)),
                ('validade', models.DateField()),
                ('codigo_seguranca', models.CharField(max_length=3)),
                ('bandeira', models.CharField(default='MC', max_length=4)),
                ('limite', models.FloatField()),
                ('limite_usado', models.FloatField(default=0)),
                ('emissao', models.DateField()),
                ('endereco_cobranca', models.CharField(max_length=12)),
                ('status', models.CharField(default='BLOQUEADO', max_length=12)),
                ('tipo', models.CharField(max_length=15)),
                ('data_vencimento_fatura', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2023, 8, 21, 19, 8, 55, 634874)),
        ),
    ]
