# Generated by Django 4.2.4 on 2023-08-22 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_creditcard_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 20, 41, 20, 960782)),
        ),
    ]
