# Generated by Django 4.2.4 on 2023-08-23 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2023, 8, 23, 11, 31, 15, 66317)),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='limite',
            field=models.FloatField(default=0),
        ),
    ]
