# Generated by Django 5.0.3 on 2024-03-08 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_endereco_cep_alter_conta_data_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='tipo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='data_abertura',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 11, 25, 3, 583985)),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
