# Generated by Django 5.0.4 on 2024-08-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_alter_cliente_cpf_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='status_conta',
            field=models.CharField(choices=[('A', 'ATIVA'), ('D', 'DESATIVADA'), ('B', 'BLOQUEADA'), ('C', 'CONGELADA'), ('E', 'ENCERRADA')], max_length=20),
        ),
    ]
