# Generated by Django 5.0.4 on 2024-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_alter_conta_status_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='status_conta',
            field=models.CharField(choices=[('A', 'ATIVA'), ('D', 'DESATIVADA'), ('B', 'BLOQUEADA'), ('C', 'CONGELADA'), ('E', 'ENCERRADA'), ('P', 'PENDENTE')], max_length=20),
        ),
    ]
