# Generated by Django 5.1 on 2024-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_chavepix'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='senha_transacao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
