# Generated by Django 4.2.4 on 2023-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_boleto_valor_alter_boleto_conta_pagador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='data_e_hora_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
