# Generated by Django 5.1 on 2024-08-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_boleto_data_e_hora_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='data_e_hora_pagamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='data_e_hora_processamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
